package com.chico.myhomebookkeeping.domain

object DefaultBelarusianNames {
    val cashAccounts = mapOf(
        "Card" to "Картка",
        "Cash" to "Наяўныя грошы"
    )

    val parentCategories = mapOf(
        "Income" to "Даходы",
        "Groceries" to "Прадукты",
        "Cafes and restaurants" to "Кафэ і рэстараны",
        "Car" to "Аўтамабіль",
        "Public transport" to "Грамадскі транспарт",
        "Home" to "Дом",
        "Clothing" to "Адзенне",
        "Health" to "Здароўе",
        "Personal Care" to "Асабісты догляд",
        "Children" to "Дзеці",
        "Pets" to "Хатнія жывёлы",
        "Mobile and internet" to "Мабільны і інтэрнэт",
        "Subscriptions & Online Services" to "Падпіскі і Інтэрнэт-сэрвісы",
        "Entertainment" to "Забавы",
        "Gifts" to "Падарункі",
        "Work" to "Праца",
        "Documents" to "Дакументы",
        "Finance" to "Фінансы"
    )

    val categories = mapOf(
        "Salary" to "Заробак",
        "Pension" to "Пенсія",
        "Side job" to "Падпрацоўка",
        "Benefits" to "Дапамогі",
        "Sick leave payments" to "Выплаты па бальнічным",
        "Gifts" to "падарункі",
        "Sales" to "Продажы",
        "Cashback" to "Кэшбэк",
        "Interest and investments" to "Працэнты і інвестыцыі",
        "Other" to "Іншае",
        "Supermarket" to "Супермаркет",
        "Market" to "Рынак",
        "Drinks" to "Напоі",
        "Grocery delivery" to "Дастаўка прадуктаў",
        "Cafe" to "Кафэ",
        "Restaurant" to "Рэстаран",
        "Fast food" to "Фастфуд",
        "Food delivery" to "Дастаўка ежы",
        "Coffee" to "Кава",
        "Loan" to "Пазыка",
        "Fuel" to "Паліва",
        "Maintenance" to "Тэхнічнае абслугоўванне",
        "Repair" to "Рамонт",
        "Insurance" to "Страхоўка",
        "Parking" to "Паркоўка",
        "Toll roads" to "Платныя дарогі",
        "Transit pass" to "Транзітны пропуск",
        "City transport" to "Гарадскі транспарт",
        "Railway" to "Чыгунка",
        "Intercity bus" to "Міжгародні аўтобус",
        "Taxi" to "Таксі",
        "Rent" to "Арэнда",
        "Utilities" to "Камунальныя паслугі",
        "Internet" to "Інтэрнэт",
        "Furniture" to "Мэбля",
        "Interior and decor" to "Інтэр'ер і дэкор",
        "Household chemicals" to "Бытавая хімія",
        "Appliances" to "Бытавая тэхніка",
        "Kitchenware" to "Кухонныя прыналежнасці",
        "Home textiles" to "Хатні тэкстыль",
        "Clothing" to "Адзенне",
        "Shoes" to "абутак",
        "Accessories" to "Аксэсуары",
        "Pharmacy" to "Аптэка",
        "Doctor" to "Доктар",
        "Dentist" to "Стаматолаг",
        "Lab tests" to "Лабараторныя даследаванні",
        "Sport" to "Спорт",
        "Hairdresser" to "Цырульнік",
        "Cosmetics" to "Касметыка",
        "Body Care" to "Сыход за целам",
        "Manicure & Pedicure" to "Манікюр і педыкюр",
        "Barbershop / Shaving" to "Цырульня / Галенне",
        "Perfume & Fragrances" to "Духі і водары",
        "Hygiene Products" to "Сродкі гігіены",
        "Kindergarten" to "Дзіцячы сад",
        "School" to "Школа",
        "Toys" to "Цацкі",
        "Clubs" to "Клубы",
        "Food" to "Корм",
        "Veterinarian" to "Ветэрынар",
        "Phone purchase" to "Купля тэлефона",
        "Phone loan" to "Крэдыт на тэлефон",
        "Mobile service" to "Мабільны сэрвіс",
        "Subscriptions" to "Падпіскі",
        "Apps" to "Праграмы",
        "Video" to "Відэа",
        "Cloud Services" to "Воблачныя сэрвісы",
        "Software & Apps" to "Праграмнае забеспячэнне і праграмы",
        "Games & Gaming Services" to "Гульні і гульнявыя сэрвісы",
        "Movies" to "фільмы",
        "Games" to "гульні",
        "Music" to "Музыка",
        "Books" to "Кнігі",
        "Hobbies" to "хобі",
        "Travel" to "Падарожжа",
        "Family" to "Сям'я",
        "Friends" to "Сябры",
        "Charity" to "Дабрачыннасць",
        "Tools" to "інструменты",
        "Stationery" to "Канцтавары",
        "Education" to "адукацыя",
        "Business trips" to "Камандзіроўкі",
        "Passport" to "Пашпарт",
        "Visa" to "Віза",
        "Permits" to "Дазволы",
        "Notary" to "Натарыус",
        "Document translation" to "Пераклад дакументаў",
        "Bank fees" to "Банкаўскія зборы",
        "Transfer fee" to "Камісія за перавод",
        "Taxes" to "Падаткі",
        "Fines" to "Штрафы",
        "Transfers" to "Пераводы"
    )

    fun parentCategoryName(canonicalName: String): String = parentCategories[canonicalName] ?: canonicalName

    fun categoryName(canonicalName: String): String = categories[canonicalName] ?: canonicalName
}
