package com.chico.myhomebookkeeping.domain

object DefaultGermanNames {
    val cashAccounts = mapOf(
        "Card" to "Karte",
        "Cash" to "Bargeld"
    )

    val parentCategories = mapOf(
        "Income" to "Einkommen",
        "Groceries" to "Lebensmittel",
        "Cafes and restaurants" to "Cafés und Restaurants",
        "Car" to "Auto",
        "Public transport" to "Öffentliche Verkehrsmittel",
        "Home" to "Zuhause",
        "Clothing" to "Kleidung",
        "Health" to "Gesundheit",
        "Personal Care" to "Körperpflege",
        "Children" to "Kinder",
        "Pets" to "Haustiere",
        "Mobile and internet" to "Mobil und Internet",
        "Subscriptions & Online Services" to "Abonnements und Onlinedienste",
        "Entertainment" to "Unterhaltung",
        "Gifts" to "Geschenke",
        "Work" to "Arbeit",
        "Documents" to "Dokumente",
        "Finance" to "Finanzen"
    )

    val categories = mapOf(
        "Salary" to "Gehalt",
        "Pension" to "Rente",
        "Side job" to "Nebenjob",
        "Benefits" to "Sozialleistungen",
        "Sick leave payments" to "Krankengeld",
        "Gifts" to "Geschenke",
        "Sales" to "Verkäufe",
        "Cashback" to "Cashback",
        "Interest and investments" to "Zinsen und Investitionen",
        "Other" to "Sonstiges",
        "Supermarket" to "Supermarkt",
        "Market" to "Markt",
        "Drinks" to "Getränke",
        "Grocery delivery" to "Lebensmittellieferung",
        "Cafe" to "Café",
        "Restaurant" to "Restaurant",
        "Fast food" to "Fastfood",
        "Food delivery" to "Essenslieferung",
        "Coffee" to "Kaffee",
        "Loan" to "Darlehen",
        "Fuel" to "Treibstoff",
        "Maintenance" to "Wartung",
        "Repair" to "Reparatur",
        "Insurance" to "Versicherung",
        "Parking" to "Parken",
        "Toll roads" to "Mautstraßen",
        "Transit pass" to "Zeitkarte",
        "City transport" to "Stadtverkehr",
        "Railway" to "Bahn",
        "Intercity bus" to "Überlandbus",
        "Taxi" to "Taxi",
        "Rent" to "Miete",
        "Utilities" to "Nebenkosten",
        "Internet" to "Internet",
        "Furniture" to "Möbel",
        "Interior and decor" to "Inneneinrichtung und Dekor",
        "Household chemicals" to "Haushaltschemikalien",
        "Appliances" to "Haushaltsgeräte",
        "Kitchenware" to "Küchenutensilien",
        "Home textiles" to "Heimtextilien",
        "Clothing" to "Kleidung",
        "Shoes" to "Schuhe",
        "Accessories" to "Zubehör",
        "Pharmacy" to "Apotheke",
        "Doctor" to "Doktor",
        "Dentist" to "Zahnarzt",
        "Lab tests" to "Labortests",
        "Sport" to "Sport",
        "Hairdresser" to "Friseur",
        "Cosmetics" to "Kosmetik",
        "Body Care" to "Körperpflege",
        "Manicure & Pedicure" to "Maniküre und Pediküre",
        "Barbershop / Shaving" to "Friseursalon / Rasieren",
        "Perfume & Fragrances" to "Parfüm und Düfte",
        "Hygiene Products" to "Hygieneprodukte",
        "Kindergarten" to "Kindergarten",
        "School" to "Schule",
        "Toys" to "Spielzeug",
        "Clubs" to "Vereine",
        "Food" to "Tierfutter",
        "Veterinarian" to "Tierarzt",
        "Phone purchase" to "Telefonkauf",
        "Phone loan" to "Telefonkredit",
        "Mobile service" to "Mobiler Service",
        "Subscriptions" to "Abonnements",
        "Apps" to "Apps",
        "Video" to "Video",
        "Cloud Services" to "Cloud-Dienste",
        "Software & Apps" to "Software & Apps",
        "Games & Gaming Services" to "Spiele und Gaming-Dienste",
        "Movies" to "Filme",
        "Games" to "Spiele",
        "Music" to "Musik",
        "Books" to "Bücher",
        "Hobbies" to "Hobbys",
        "Travel" to "Reisen",
        "Family" to "Familie",
        "Friends" to "Freunde",
        "Charity" to "Wohltätigkeit",
        "Tools" to "Werkzeuge",
        "Stationery" to "Schreibwaren",
        "Education" to "Bildung",
        "Business trips" to "Geschäftsreisen",
        "Passport" to "Reisepass",
        "Visa" to "Visum",
        "Permits" to "Genehmigungen",
        "Notary" to "Notar",
        "Document translation" to "Dokumentenübersetzung",
        "Bank fees" to "Bankgebühren",
        "Transfer fee" to "Überweisungsgebühr",
        "Taxes" to "Steuern",
        "Fines" to "Geldstrafen",
        "Transfers" to "Überweisungen"
    )

    fun parentCategoryName(canonicalName: String): String = parentCategories[canonicalName] ?: canonicalName

    fun categoryName(canonicalName: String): String = categories[canonicalName] ?: canonicalName
}
