package com.chico.myhomebookkeeping.domain

object DefaultPolishNames {
    val cashAccounts = mapOf(
        "Card" to "Karta",
        "Cash" to "Gotówka"
    )

    val parentCategories = mapOf(
        "Income" to "Przychody",
        "Groceries" to "Zakupy spożywcze",
        "Cafes and restaurants" to "Kawiarnie i restauracje",
        "Car" to "Samochód",
        "Public transport" to "Transport publiczny",
        "Home" to "Dom",
        "Clothing" to "Odzież",
        "Health" to "Zdrowie",
        "Personal Care" to "Higiena i pielęgnacja",
        "Children" to "Dzieci",
        "Pets" to "Zwierzęta",
        "Mobile and internet" to "Telefon i internet",
        "Entertainment" to "Rozrywka",
        "Gifts" to "Prezenty",
        "Work" to "Praca",
        "Documents" to "Dokumenty",
        "Finance" to "Finanse"
    )

    val categories = mapOf(
        "Salary" to "Pensja",
        "Pension" to "Emerytura",
        "Side job" to "Praca dodatkowa",
        "Benefits" to "Świadczenia",
        "Gifts" to "Prezenty",
        "Sales" to "Sprzedaż",
        "Cashback" to "Cashback",
        "Interest and investments" to "Odsetki i inwestycje",
        "Other" to "Inne",
        "Supermarket" to "Supermarket",
        "Market" to "Rynek",
        "Drinks" to "Napoje",
        "Grocery delivery" to "Dostawa zakupów",
        "Cafe" to "Kawiarnia",
        "Restaurant" to "Restauracja",
        "Fast food" to "Fast food",
        "Food delivery" to "Dostawa jedzenia",
        "Coffee" to "Kawa",
        "Loan" to "Kredyt",
        "Fuel" to "Paliwo",
        "Maintenance" to "Serwis",
        "Repair" to "Naprawa",
        "Insurance" to "Ubezpieczenie",
        "Parking" to "Parking",
        "Toll roads" to "Drogi płatne",
        "Transit pass" to "Bilet okresowy",
        "City transport" to "Transport miejski",
        "Railway" to "Kolej",
        "Intercity bus" to "Autobus międzymiastowy",
        "Taxi" to "Taksówka",
        "Rent" to "Czynsz",
        "Utilities" to "Media",
        "Internet" to "Internet",
        "Furniture" to "Meble",
        "Interior and decor" to "Wnętrze i dekoracje",
        "Household chemicals" to "Chemia domowa",
        "Appliances" to "Sprzęt AGD",
        "Kitchenware" to "Akcesoria kuchenne",
        "Home textiles" to "Tekstylia domowe",
        "Clothing" to "Ubrania",
        "Shoes" to "Buty",
        "Accessories" to "Akcesoria",
        "Pharmacy" to "Apteka",
        "Doctor" to "Lekarz",
        "Dentist" to "Dentysta",
        "Lab tests" to "Badania",
        "Sport" to "Sport",
        "Hairdresser" to "Fryzjer",
        "Cosmetics" to "Kosmetyki",
        "Body Care" to "Pielęgnacja ciała",
        "Manicure & Pedicure" to "Manicure i pedicure",
        "Barbershop / Shaving" to "Barber / golenie",
        "Perfume & Fragrances" to "Perfumy i zapachy",
        "Hygiene Products" to "Produkty higieniczne",
        "Kindergarten" to "Przedszkole",
        "School" to "Szkoła",
        "Toys" to "Zabawki",
        "Clubs" to "Zajęcia dodatkowe",
        "Food" to "Karma",
        "Veterinarian" to "Weterynarz",
        "Phone purchase" to "Zakup telefonu",
        "Phone loan" to "Kredyt na telefon",
        "Mobile service" to "Usługi komórkowe",
        "Subscriptions" to "Subskrypcje",
        "Apps" to "Aplikacje",
        "Movies" to "Filmy",
        "Games" to "Gry",
        "Music" to "Muzyka",
        "Books" to "Książki",
        "Hobbies" to "Hobby",
        "Travel" to "Podróże",
        "Family" to "Rodzina",
        "Friends" to "Znajomi",
        "Charity" to "Dobroczynność",
        "Tools" to "Narzędzia",
        "Stationery" to "Artykuły biurowe",
        "Education" to "Edukacja",
        "Business trips" to "Podróże służbowe",
        "Passport" to "Paszport",
        "Visa" to "Wiza",
        "Permits" to "Zezwolenia",
        "Notary" to "Notariusz",
        "Document translation" to "Tłumaczenie dokumentów",
        "Bank fees" to "Opłaty bankowe",
        "Transfer fee" to "Opłata za przelew",
        "Taxes" to "Podatki",
        "Fines" to "Mandaty",
        "Transfers" to "Przelewy"
    )

    fun parentCategoryName(canonicalName: String): String = parentCategories[canonicalName] ?: canonicalName

    fun categoryName(canonicalName: String): String = categories[canonicalName] ?: canonicalName
}
