package com.chico.myhomebookkeeping.enums.icons

enum class CategoryIconNames {
    Apartment,
    Airplane,
    ArrowsHorizontal,
    ArrowDropDown,
    ArrowDropUp,
    Build,
    Bus,
    Cake,
    Car,
    Celebration,
    ChildFriendly,
    Coffee,
    Computer,
    GasStation,
    House,
    Medical,
    Park,
    PedalBike,
    People,
    Person,
    Pets,
    Phone,
    PhoneAndroid,
    PhoneIphone,
    Restaurant,
    Salon,
    School,
    ShoppingCart,
    ShoppingCartAdd,
    Store,
    Subway,
    TwoWheeler,
    Bank
}